/* climate.js — Global Climate Explorer
   Expects: data/climate_data.json  (generated by the Colab export script)
   Libs:    D3 v7
*/

(async function () {

  // ── Load data ──────────────────────────────────────────────────────────────
  // GeoJSON with properties.name using Natural Earth names — matches regionmask
  const GEO_URL = 'https://cdn.jsdelivr.net/gh/holtzy/D3-graph-gallery@master/DATA/world.geojson';

  let geoData, climateData;
  try {
    [geoData, climateData] = await Promise.all([
      d3.json(GEO_URL),
      d3.json('data/climate_data.json'),
    ]);
  } catch (e) {
    document.getElementById('map-view').innerHTML =
      '<p style="color:#ff6b6b;padding:3rem;font-size:1rem">' +
      '⚠ Could not load data/climate_data.json. ' +
      'Run export_data.py in Colab first, then place the file in the data/ folder.</p>';
    return;
  }

  const countries = geoData;

  // ── Color scale (warming anomaly → yellow/orange/red) ─────────────────────
  const COLOR_DOMAIN = [0, 3];
  const colorScale = d3.scaleSequential()
    .domain(COLOR_DOMAIN)
    .interpolator(d3.interpolateYlOrRd);

  const NO_DATA_COLOR = '#1e2530';

  // ── World Map ──────────────────────────────────────────────────────────────
  const mapSvg  = d3.select('#world-map');
  const mapNode = mapSvg.node();

  function buildMap() {
    const W = mapNode.clientWidth || 960;
    const H = Math.round(W * 0.5);
    mapNode.style.height = H + 'px';
    mapSvg.attr('viewBox', `0 0 ${W} ${H}`);

    const projection = d3.geoNaturalEarth1().fitSize([W, H], { type: 'Sphere' });
    const path = d3.geoPath().projection(projection);

    mapSvg.selectAll('*').remove();

    // Ocean
    mapSvg.append('rect').attr('width', W).attr('height', H).attr('fill', '#090e1a');

    // Graticule
    mapSvg.append('path')
      .datum(d3.geoGraticule()())
      .attr('d', path)
      .attr('fill', 'none')
      .attr('stroke', '#151d2b')
      .attr('stroke-width', 0.4);

    // Sphere border
    mapSvg.append('path')
      .datum({ type: 'Sphere' })
      .attr('d', path)
      .attr('fill', 'none')
      .attr('stroke', '#30363d')
      .attr('stroke-width', 0.6);

    // Countries
    mapSvg.selectAll('.country')
      .data(countries.features)
      .join('path')
      .attr('class', d => 'country' + (climateData[d.properties.name] ? ' has-data' : ''))
      .attr('d', path)
      .attr('fill', d => {
        const cd = climateData[d.properties.name];
        return cd ? colorScale(cd.anomaly) : NO_DATA_COLOR;
      })
      .attr('stroke', '#0d1117')
      .attr('stroke-width', 0.4)
      .on('mouseover', onMouseOver)
      .on('mousemove', onMouseMove)
      .on('mouseout',  onMouseOut)
      .on('click',     onCountryClick);
  }

  buildMap();
  window.addEventListener('resize', buildMap);

  // ── Legend ─────────────────────────────────────────────────────────────────
  (function drawLegend() {
    const svg = d3.select('#legend-svg');
    const W = 160, H = 14;
    svg.attr('width', W).attr('height', H);
    const defs = svg.append('defs');
    const grad = defs.append('linearGradient').attr('id', 'leg-grad');
    d3.range(11).forEach(i => {
      grad.append('stop')
        .attr('offset', `${i * 10}%`)
        .attr('stop-color', colorScale(i * COLOR_DOMAIN[1] / 10));
    });
    svg.append('rect').attr('width', W).attr('height', H).attr('rx', 3)
      .attr('fill', 'url(#leg-grad)');
  })();

  // ── Tooltip ────────────────────────────────────────────────────────────────
  const tooltip = document.getElementById('tooltip');

  function onMouseOver(event, d) {
    const cd = climateData[d.properties.name];
    if (!cd) return;
    const sign = cd.anomaly >= 0 ? '+' : '';
    tooltip.innerHTML =
      `<div class="tt-name">${cd.name}</div>` +
      `<div class="tt-val">${sign}${cd.anomaly.toFixed(2)}°C vs 1850–1900</div>` +
      `<div class="tt-hint">Click to explore</div>`;
    tooltip.classList.add('visible');
  }

  function onMouseMove(event) {
    tooltip.style.left = (event.clientX + 14) + 'px';
    tooltip.style.top  = (event.clientY - 10) + 'px';
  }

  function onMouseOut() {
    tooltip.classList.remove('visible');
  }

  // ── State ──────────────────────────────────────────────────────────────────
  let activeCountry  = null;
  let currentMetric  = 'annual';
  let yearStart      = 1850;
  let yearEnd        = 2014;

  // ── Country click → drill-down ─────────────────────────────────────────────
  function onCountryClick(event, d) {
    const cd = climateData[d.properties.name];
    if (!cd) return;

    activeCountry = cd;
    yearStart = 1850;
    yearEnd   = 2014;

    // Reset sliders
    document.getElementById('slider-start').value = 1850;
    document.getElementById('slider-end').value   = 2014;
    document.getElementById('lbl-start').textContent = 1850;
    document.getElementById('lbl-end').textContent   = 2014;

    // Header
    document.getElementById('country-name').textContent = cd.name;
    const sign = cd.anomaly >= 0 ? '+' : '';
    document.getElementById('country-stat').textContent =
      `${sign}${cd.anomaly.toFixed(2)}°C warmer than 1850–1900 (2000–2014 average)`;

    // Reset tabs
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelector('[data-metric="annual"]').classList.add('active');
    currentMetric = 'annual';

    // Swap views
    document.getElementById('map-view').classList.add('hidden');
    document.getElementById('detail-view').classList.add('visible');
    tooltip.classList.remove('visible');

    drawDetailChart();
  }

  // ── Back button ────────────────────────────────────────────────────────────
  document.getElementById('back-btn').addEventListener('click', () => {
    document.getElementById('detail-view').classList.remove('visible');
    document.getElementById('map-view').classList.remove('hidden');
    activeCountry = null;
  });

  // ── Metric tabs ────────────────────────────────────────────────────────────
  document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      currentMetric = btn.dataset.metric;
      if (activeCountry) drawDetailChart();
    });
  });

  // ── Year sliders ───────────────────────────────────────────────────────────
  document.getElementById('slider-start').addEventListener('input', function () {
    yearStart = +this.value;
    if (yearStart > yearEnd) { yearStart = yearEnd; this.value = yearStart; }
    document.getElementById('lbl-start').textContent = yearStart;
    if (activeCountry) drawDetailChart();
  });

  document.getElementById('slider-end').addEventListener('input', function () {
    yearEnd = +this.value;
    if (yearEnd < yearStart) { yearEnd = yearStart; this.value = yearEnd; }
    document.getElementById('lbl-end').textContent = yearEnd;
    if (activeCountry) drawDetailChart();
  });

  // ── Detail chart dispatcher ────────────────────────────────────────────────
  function drawDetailChart() {
    const svgEl  = document.getElementById('detail-chart');
    const totalW = svgEl.clientWidth || 860;
    const totalH = 400;
    const m = { top: 24, right: 36, bottom: 56, left: 66 };
    const W = totalW - m.left - m.right;
    const H = totalH - m.top  - m.bottom;

    const svg = d3.select('#detail-chart')
      .attr('width', totalW)
      .attr('height', totalH);

    svg.selectAll('*').remove();

    const g = svg.append('g').attr('transform', `translate(${m.left},${m.top})`);

    if (currentMetric === 'annual') drawAnnual(g, W, H);
    else                             drawDecadal(g, W, H);
  }

  // ── Annual anomaly line chart ──────────────────────────────────────────────
  function drawAnnual(g, W, H) {
    const data = activeCountry.timeseries.filter(d => d.year >= yearStart && d.year <= yearEnd);
    if (data.length === 0) return;

    const rolled = rollingMean(data, 10);

    const x = d3.scaleLinear().domain([yearStart, yearEnd]).range([0, W]);
    const allY = [...data.map(d => d.anomaly), ...rolled.filter(r => r.m != null).map(r => r.m)];
    const y = d3.scaleLinear().domain(d3.extent(allY)).nice().range([H, 0]);

    // Horizontal grid lines
    g.append('g').selectAll('.grid-line')
      .data(y.ticks(5))
      .join('line').attr('class', 'grid-line')
      .attr('x1', 0).attr('x2', W)
      .attr('y1', d => y(d)).attr('y2', d => y(d));

    // Zero line
    if (y.domain()[0] < 0 && y.domain()[1] > 0) {
      g.append('line').attr('class', 'zero-line')
        .attr('x1', 0).attr('x2', W)
        .attr('y1', y(0)).attr('y2', y(0));
    }

    // Shaded area under/above zero
    g.append('path')
      .datum(data)
      .attr('fill', '#ff6b6b').attr('opacity', 0.07)
      .attr('d', d3.area()
        .x(d => x(d.year))
        .y0(y(Math.max(y.domain()[0], 0)))
        .y1(d => y(d.anomaly))
        .curve(d3.curveMonotoneX));

    // Raw annual (faint)
    g.append('path')
      .datum(data)
      .attr('fill', 'none')
      .attr('stroke', '#ff6b6b').attr('stroke-width', 1).attr('opacity', 0.35)
      .attr('d', d3.line().x(d => x(d.year)).y(d => y(d.anomaly)).curve(d3.curveMonotoneX));

    // 10-yr rolling mean (bold)
    const cleanRolled = rolled.filter(r => r.m != null);
    if (cleanRolled.length > 0) {
      g.append('path')
        .datum(cleanRolled)
        .attr('fill', 'none')
        .attr('stroke', '#ff6b6b').attr('stroke-width', 2.8)
        .attr('d', d3.line().x(d => x(d.year)).y(d => y(d.m)).curve(d3.curveMonotoneX));
    }

    // Axes
    g.append('g').attr('class', 'axis')
      .attr('transform', `translate(0,${H})`)
      .call(d3.axisBottom(x).tickFormat(d3.format('d')).ticks(8));

    g.append('g').attr('class', 'axis')
      .call(d3.axisLeft(y).tickFormat(d => `${d >= 0 ? '+' : ''}${d.toFixed(1)}°C`));

    // Axis labels
    g.append('text').attr('class', 'axis-label')
      .attr('x', W / 2).attr('y', H + 44).attr('text-anchor', 'middle')
      .text('Year');

    g.append('text').attr('class', 'axis-label')
      .attr('transform', 'rotate(-90)')
      .attr('x', -H / 2).attr('y', -52).attr('text-anchor', 'middle')
      .text('Anomaly vs 1850–1900 (°C)');

    // Legend
    const leg = g.append('g').attr('transform', `translate(${W - 160}, 0)`);
    leg.append('line').attr('x2', 18).attr('y1', 8).attr('y2', 8)
      .attr('stroke', '#ff6b6b').attr('stroke-width', 1).attr('opacity', 0.4);
    leg.append('text').attr('class', 'legend-text').attr('x', 22).attr('y', 12).text('Annual');
    leg.append('line').attr('x2', 18).attr('y1', 26).attr('y2', 26)
      .attr('stroke', '#ff6b6b').attr('stroke-width', 2.8);
    leg.append('text').attr('class', 'legend-text').attr('x', 22).attr('y', 30).text('10-yr rolling mean');
  }

  // ── Decadal bar chart ──────────────────────────────────────────────────────
  function drawDecadal(g, W, H) {
    const data = activeCountry.decadal.filter(d => d.year >= yearStart && d.year <= yearEnd);
    if (data.length === 0) return;

    const x = d3.scaleBand().domain(data.map(d => d.decade)).range([0, W]).padding(0.22);
    const yMin = Math.min(0, d3.min(data, d => d.anomaly) - 0.05);
    const yMax = d3.max(data, d => d.anomaly) + 0.08;
    const y = d3.scaleLinear().domain([yMin, yMax]).nice().range([H, 0]);

    const barColor = d3.scaleSequential()
      .domain([0, 2.5])
      .interpolator(d3.interpolateYlOrRd);

    // Grid
    g.append('g').selectAll('.grid-line')
      .data(y.ticks(5)).join('line').attr('class', 'grid-line')
      .attr('x1', 0).attr('x2', W)
      .attr('y1', d => y(d)).attr('y2', d => y(d));

    // Zero line
    g.append('line').attr('class', 'zero-line')
      .attr('x1', 0).attr('x2', W).attr('y1', y(0)).attr('y2', y(0));

    // Bars
    g.selectAll('.bar').data(data).join('rect').attr('class', 'bar')
      .attr('x',      d => x(d.decade))
      .attr('width',  x.bandwidth())
      .attr('y',      d => d.anomaly >= 0 ? y(d.anomaly) : y(0))
      .attr('height', d => Math.abs(y(d.anomaly) - y(0)))
      .attr('fill',   d => barColor(Math.max(0, d.anomaly)))
      .attr('rx', 3);

    // Value labels
    g.selectAll('.bar-label').data(data).join('text').attr('class', 'bar-label')
      .attr('x', d => x(d.decade) + x.bandwidth() / 2)
      .attr('y', d => d.anomaly >= 0 ? y(d.anomaly) - 5 : y(d.anomaly) + 13)
      .attr('text-anchor', 'middle')
      .text(d => `${d.anomaly >= 0 ? '+' : ''}${d.anomaly.toFixed(2)}`);

    // Axes
    g.append('g').attr('class', 'axis')
      .attr('transform', `translate(0,${H})`)
      .call(d3.axisBottom(x))
      .selectAll('text')
      .attr('transform', 'rotate(-40)')
      .style('text-anchor', 'end');

    g.append('g').attr('class', 'axis')
      .call(d3.axisLeft(y).tickFormat(d => `${d >= 0 ? '+' : ''}${d.toFixed(1)}°C`));

    // Axis labels
    g.append('text').attr('class', 'axis-label')
      .attr('x', W / 2).attr('y', H + 50).attr('text-anchor', 'middle')
      .text('Decade');

    g.append('text').attr('class', 'axis-label')
      .attr('transform', 'rotate(-90)')
      .attr('x', -H / 2).attr('y', -52).attr('text-anchor', 'middle')
      .text('Anomaly vs 1850–1900 (°C)');
  }

  // ── Utility: centered rolling mean ────────────────────────────────────────
  function rollingMean(data, w) {
    const half = Math.floor(w / 2);
    return data.map((d, i) => {
      const slice = data.slice(Math.max(0, i - half), Math.min(data.length, i + half + 1));
      const m = slice.length >= half ? d3.mean(slice, s => s.anomaly) : null;
      return { year: d.year, m };
    });
  }

})();
